### obtener todos los user(get all)
GET http://localhost:3000/api/users
### obtener un user(get one)
GET http://localhost:3000/api/users/1

### crear un nuevo user
POST http://localhost:3000/api/users/register
Content-Type: application/json

 {
  "realname": "Pedro Omar",
  "surname": "Coutinho",
  "username": "Couti",
  "birth_date": "2024-04-16T00:04:12.275Z",
  "creationuser": "sarasa",
  "status": true,
  "password": "Paraguay574",
  "salt": "salt_aleatorio"
}



### modificar un user 
PUT http://localhost:3000/api/users/4
Content-Type: application/json

 {
  "realname": "Maximiliano",
  "surname": "Rodriguez",
  "modificationuser": "Maxi",
  "modificationtimestamp": "2024-04-16T00:04:12.275Z",
  "status": true
}

### borrar un user
DELETE http://localhost:3000/api/users/2
